name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarming
version: 1.4
depend: [Arconix]
soft-depend: [Multiverse-Core]
author: Songoda
api-version: 1.13
commands:
  EpicFarming:
    description: View information on this plugin.
    default: true
    aliases: [efa]
    usage: /ed