name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarming
version: maven-version-number
softdepend: [Arconix, SkyBlock, Towny, RedProtect, Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, PlaceholderAPI, Vault, PlayerPoints, Reserve]
author: Songoda
api-version: 1.13
commands:
  EpicFarming:
    description: View information on this plugin.
    default: true
    aliases: [efa]
    usage: /efa