name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarming
version: 1.2.1
depend: [Arconix]
author: Songoda
commands:
  EpicFarming:
    description: View information on this plugin.
    default: true
    aliases: [efa]
    usage: /ed