name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarming
version: maven-version-number
softdepend: [FabledSkyBlock, Arconix, SkyBlock, Towny, RedProtect, Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, PlaceholderAPI, Vault, PlayerPoints, Reserve, StackMob, UltimateStacker, WildStacker]
author: Songoda
api-version: 1.13
commands:
  EFA:
    description: View information on this plugin.
    default: true
    aliases: [EpicFarming]
    usage: /efa