name: EpicFarming
description: EpicFarming
main: com.songoda.epicfarming.EpicFarmingPlugin
version: maven-version-number
soft-depend: [Multiverse-Core]
author: Songoda
api-version: 1.13
commands:
  EpicFarming:
    description: View information on this plugin.
    default: true
    aliases: [efa]
    usage: /efa